# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 19:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'cities',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FacebookUsers',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'facebook_users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StationExamples',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'station-examples',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stations',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('house', models.SmallIntegerField()),
                ('building', models.SmallIntegerField(blank=True, null=True)),
                ('raiting', models.SmallIntegerField(blank=True, null=True)),
                ('position_x', models.FloatField(blank=True, null=True)),
                ('position_y', models.FloatField(blank=True, null=True)),
                ('add_date', models.DateField()),
                ('update_date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'stations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StationTypes',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'station_types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Streets',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'streets',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TrashClasses',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'trash_classes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TrashExamples',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'trash_examples',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TrashTypes',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'trash_types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=30, unique=True)),
                ('password', models.BigIntegerField(unique=True)),
                ('reg_date', models.DateField()),
                ('raiting', models.IntegerField()),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsersExamples',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'users-examples',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VkUsers',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'vk_users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserSocialnet',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='re_admin.Users')),
            ],
            options={
                'db_table': 'user-socialnet',
                'managed': False,
            },
        ),
    ]
