# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 19:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'cities',
                'managed': True,
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='FacebookUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'facebook_users',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('house', models.SmallIntegerField()),
                ('building', models.SmallIntegerField(null=True)),
                ('raiting', models.SmallIntegerField(null=True)),
                ('position_x', models.FloatField(null=True)),
                ('position_y', models.FloatField(null=True)),
                ('add_date', models.DateField()),
                ('update_date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'stations',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='re_app.City')),
            ],
            options={
                'db_table': 'streets',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Trash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'trash',
                'managed': True,
                'verbose_name_plural': 'Trash',
            },
        ),
        migrations.CreateModel(
            name='TrashClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'trash_classes',
                'managed': True,
                'verbose_name_plural': 'Trash classes',
            },
        ),
        migrations.CreateModel(
            name='TrashStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='re_app.Station')),
            ],
            options={
                'db_table': 'trash-stations',
                'managed': True,
                'verbose_name_plural': 'Trash-Stations',
            },
        ),
        migrations.CreateModel(
            name='TrashType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'trash_types',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=30, unique=True)),
                ('password', models.BigIntegerField(unique=True)),
                ('reg_date', models.DateField()),
                ('raiting', models.IntegerField()),
            ],
            options={
                'db_table': 'users',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserSocialnet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='re_app.FacebookUser')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='re_app.User')),
            ],
            options={
                'db_table': 'user-socialnet',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserTrash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='re_app.Trash')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='re_app.User')),
            ],
            options={
                'db_table': 'users-trash',
                'managed': True,
                'verbose_name_plural': 'User-Trash',
            },
        ),
        migrations.CreateModel(
            name='VkUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'vk_users',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='usersocialnet',
            name='vk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='re_app.VkUser'),
        ),
        migrations.AddField(
            model_name='trashstation',
            name='trash_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='re_app.TrashType'),
        ),
        migrations.AddField(
            model_name='trash',
            name='class_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='re_app.TrashClass', verbose_name='class'),
        ),
        migrations.AddField(
            model_name='trash',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='re_app.TrashType'),
        ),
        migrations.AddField(
            model_name='station',
            name='street',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='re_app.Street'),
        ),
    ]
