# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('re_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='building',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='raiting',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
