# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('re_app', '0007_auto_20160702_1253'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trashstation',
            options={'managed': True, 'verbose_name': '\u043e\u0431\u044a\u0435\u043a\u0442', 'verbose_name_plural': '\u043e\u0431\u044a\u0435\u043a\u0442\u044b'},
        ),
        migrations.AlterModelOptions(
            name='usertrash',
            options={'managed': True, 'verbose_name': '\u043e\u0431\u044a\u0435\u043a\u0442', 'verbose_name_plural': '\u043e\u0431\u044a\u0435\u043a\u0442\u044b'},
        ),
        migrations.AddField(
            model_name='station',
            name='nof_use',
            field=models.IntegerField(default=0, verbose_name='\u041f\u043e\u043f\u0443\u043b\u044f\u0440\u043d\u043e\u0441\u0442\u044c'),
        ),
        migrations.AddField(
            model_name='station',
            name='telephone',
            field=models.CharField(max_length=20, null=True, verbose_name='\u0422\u0435\u043b\u0435\u0444\u043e\u043d'),
        ),
        migrations.AddField(
            model_name='station',
            name='time_close',
            field=models.TimeField(blank=True, null=True, verbose_name='\u0417\u0430\u043a\u0440\u044b\u0432\u0430\u0435\u0442\u044c\u0441\u044f \u0432'),
        ),
        migrations.AddField(
            model_name='station',
            name='time_open',
            field=models.TimeField(blank=True, null=True, verbose_name='\u041e\u0442\u043a\u0440\u044b\u0432\u0430\u0435\u0442\u0441\u044f \u0432'),
        ),
        migrations.AlterField(
            model_name='station',
            name='raiting',
            field=models.SmallIntegerField(blank=True, default=0, verbose_name='\u0420\u044d\u0439\u0442\u0438\u043d\u0433'),
        ),
        migrations.AlterField(
            model_name='station',
            name='show',
            field=models.BooleanField(default=False, verbose_name='\u041d\u0430 \u043a\u0430\u0440\u0442\u0435'),
        ),
    ]
