# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('re_app', '0009_auto_20160706_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='\u0422\u0435\u043b\u0435\u0444\u043e\u043d'),
        ),
    ]
