# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 09:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('re_app', '0010_auto_20160706_2351'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_open', models.CharField(choices=[('\u041f\u043d', '\u041f\u043e\u043d\u0435\u0434\u0435\u043b\u044c\u043d\u0438\u043a'), ('\u0412\u0442', '\u0412\u0442\u043e\u0440\u043d\u0438\u043a'), ('\u0421\u0440', '\u0421\u0440\u0435\u0434\u0430'), ('\u0427\u0442', '\u0427\u0435\u0442\u0432\u0435\u0440\u0433'), ('\u041f\u0442', '\u041f\u044f\u0442\u043d\u0438\u0446\u0430'), ('\u0421\u0431', '\u0421\u0443\u0431\u0431\u043e\u0442\u0430'), ('\u0412\u0441', '\u0412\u043e\u0441\u043a\u0440\u0435\u0441\u0435\u043d\u0438\u0435')], default='\u041f\u043d', max_length=2, verbose_name='\u0420\u0430\u0431\u043e\u0442\u0430\u0435\u0442 \u0441')),
                ('day_close', models.CharField(choices=[('\u041f\u043d', '\u041f\u043e\u043d\u0435\u0434\u0435\u043b\u044c\u043d\u0438\u043a'), ('\u0412\u0442', '\u0412\u0442\u043e\u0440\u043d\u0438\u043a'), ('\u0421\u0440', '\u0421\u0440\u0435\u0434\u0430'), ('\u0427\u0442', '\u0427\u0435\u0442\u0432\u0435\u0440\u0433'), ('\u041f\u0442', '\u041f\u044f\u0442\u043d\u0438\u0446\u0430'), ('\u0421\u0431', '\u0421\u0443\u0431\u0431\u043e\u0442\u0430'), ('\u0412\u0441', '\u0412\u043e\u0441\u043a\u0440\u0435\u0441\u0435\u043d\u0438\u0435')], default='\u0412\u0441', max_length=2, verbose_name='\u043f\u043e')),
                ('time_open', models.TimeField(blank=True, null=True, verbose_name='\u041e\u0442\u043a\u0440\u044b\u0432\u0430\u0435\u0442\u0441\u044f \u0432')),
                ('time_close', models.TimeField(blank=True, null=True, verbose_name='\u0417\u0430\u043a\u0440\u044b\u0432\u0430\u0435\u0442\u044c\u0441\u044f \u0432')),
            ],
            options={
                'verbose_name': '\u0413\u0440\u0430\u0432\u0438\u043a \u0440\u0430\u0431\u043e\u0442\u044b',
                'db_table': 'schedule',
                'managed': True,
                'verbose_name_plural': '\u0413\u0440\u0444\u0438\u043a\u0438 \u0440\u0430\u0431\u043e\u0442\u044b',
            },
        ),
        migrations.RemoveField(
            model_name='station',
            name='day_close',
        ),
        migrations.RemoveField(
            model_name='station',
            name='day_open',
        ),
        migrations.RemoveField(
            model_name='station',
            name='time_close',
        ),
        migrations.RemoveField(
            model_name='station',
            name='time_open',
        ),
        migrations.AlterField(
            model_name='station',
            name='street',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='re_app.Street', verbose_name='\u0423\u043b\u0438\u0446\u0430'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='station_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='re_app.Station', verbose_name='\u0421\u0442\u0430\u043d\u0446\u0438\u044f \u0443\u0442\u0438\u043b\u0438\u0437\u0430\u0446\u0438\u0438'),
        ),
    ]
