# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('re_app', '0011_auto_20160707_1231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='station_id',
            new_name='station',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='time_close',
            field=models.TimeField(default=b'18:00', verbose_name='\u0417\u0430\u043a\u0440\u044b\u0432\u0430\u0435\u0442\u044c\u0441\u044f \u0432'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='time_open',
            field=models.TimeField(default=b'09:00', verbose_name='\u041e\u0442\u043a\u0440\u044b\u0432\u0430\u0435\u0442\u0441\u044f \u0432'),
        ),
    ]
