# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('re_app', '0012_auto_20160707_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='all_day',
            field=models.BooleanField(default=False, verbose_name='\u041a\u0440\u0443\u0433\u043b\u043e\u0441\u0443\u0442\u043e\u0447\u043d\u043e'),
        ),
    ]
